# Identification du projet
sonar.projectKey=user-management
sonar.projectName=user-management
sonar.projectVersion=1.0

# Chemins du projet
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Encodage
sonar.sourceEncoding=UTF-8

# Serveur SonarQube
sonar.host.url=http://localhost:9000

# Authentification (via GitHub Actions)
sonar.login=${SONAR_TOKEN}
